### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by ayhyap** [veerendra2/dictionaries#1]
I have a feeling this was intentional ;)

(404 is missing from the code dictionary)

EDIT: upon closer inspection, it looks like 403 has 404's wikipedia description, and 404 is just missing.

**Comment by veerendra2** [comment]
Wow!, I don't know how did miss the famous `http error 404`. Thanks anyway. Added now :-) https://github.com/veerendra2/dictionaries/commit/916cb079da4dc82c9933010111ce037e1fca54f0
